### PR TITLE
Deprecate in favour of `critical_section`.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by adamgreig** [comment]
I think the plan we discussed is to re-export `CriticalSection` and `Mutex` from `critical-section` and publish that as a new release, and simultaneously (or later) deprecate the crate. That way, people using the current types can immediately gain compatibility with `critical-section`, and the types are already identical for this reason.

**Comment by reitermarkus** [comment]
So just leave 1.0 alone without any deprecation?

If people need to upgrade `bare_metal` to 2.0 just for it to show the deprecation, they might as well switch to `critical_section` 1.0 immediately instead which takes only marginally more work.

**Comment by adamgreig** [comment]
The idea was to publish 1.1 with the re-exported `critical-section` types, and also mark them (or the whole crate) as deprecated.

**Comment by reitermarkus** [comment]
I thought we'd need to release 2.0 since the MSRV of `critical_section` is higher.

**Comment by adamgreig** [comment]
We don't consider increasing the MSRV to be a breaking change, so we can release 1.1 with a higher MSRV.

**Comment by reitermarkus** [comment]
Okay, I will change this then to re-export the types from `critical_section` instead.

**Review by adamgreig — APPROVED** [review]
LGTM. Is there any particular reason to prefer `type CriticalSection<'cs> = critical_section::CriticalSection<'cs>` over `pub use critical_section::CriticalSection`? Maybe clearer documentation?

**Comment by reitermarkus** [comment]
The `deprecate` attribute doesn't work on re-exports.

**Review by adamgreig — APPROVED** [review]
Thanks! I think this is fine, I'll add some notes to the README later but probably hold off on publishing for a few more weeks until we see more widespread adoption of critical-section and hopefully resolve the potential bloat issues on msp430.

bors r+

**Comment by adamgreig** [comment]
Could you update the required bors status in https://github.com/rust-embedded/bare-metal/blob/master/.github/bors.toml#L8 for the new MSRV?

**Review by adamgreig — APPROVED** [review]
bors retry

**Pull request merged**
